### ISSUE TITLE
itsdangerous-php on Pakagist

### ISSUE THREAD

**Issue by energyhousedigital** [mattbasta/itsdangerous-php#8]
Really love your library, so any chance this can go to Packagist?
https://packagist.org/

**Comment by mattbasta** [comment]
I'll look into it and get to it eventually. I can't guarantee when, though. If you'd like to submit a `composer.json` file or commit any tweaks to make it easier to package, I'd be happy to merge it.

**Comment by energyhousedigital** [comment]
I can do it, however an account must be created on Packagist and probably has to be the owner of the project.
I'll give it a try anyway.
Thanks.
